language: csharp
dist: focal
sudo: required
mono: none

os:
  - linux
  - osx
  - windows
  
solution: MetarDecoder.sln
env:
  global:
    - ResolveNuGetPackageAssets=true
    - EnableNuGetPackageRestore=true
    - DOTNETCORE=5
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_install:
- |
    if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      choco install dotnet-sdk --version=5.0.302
      dotnet restore MetarDecoder.sln --ignore-failed-sources --configfile nuget.config
    fi
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 5.0
      PATH=$PATH:/home/travis/.dotnet
    fi
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 5.0
      PATH=$PATH:/Users/travis/.dotnet
    fi
install:
  - dotnet restore MetarDecoder.sln --ignore-failed-sources
script:
  - dotnet build MetarDecoder.sln --configuration Release --verbosity minimal --no-incremental --ignore-failed-sources
cache:
  directories:
    - bin
