name: Auto Create PR to Develop

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'fix/**'
      - 'bug/**'
      - 'openhands**'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ github.ref_name }}
      commit_sha_short: ${{ steps.vars.outputs.commit_sha_short }}
      commit_message: ${{ steps.vars.outputs.commit_message }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for better commit messages if needed

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: | 
          6.0.x
          8.0.x
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x' # As used in Build-all-and-test.yml

      - name: Restore .NET Dependencies 
        run: dotnet restore MetarDecoder.sln --ignore-failed-sources
        
      - name: Build Solution (Debug)
        run: dotnet build MetarDecoder.sln --configuration Debug

      - name: Run Tests
        run: dotnet test MetarDecoder.sln --no-build --verbosity normal --configuration Debug /p:TargetFramework=net8.0

      - name: Get commit details
        id: vars
        run: |
          echo "commit_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT


  create_pr:
    name: Create Pull Request
    needs: build_and_test
    if: success() # Only run if build_and_test succeeded
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write # Some PR actions might need this to manage branches or push updates

    steps:
      - name: Checkout code (needed by create-pull-request action)
        uses: actions/checkout@v4

      - name: Create Pull Request to develop
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-PR: Updates for ${{ needs.build_and_test.outputs.branch_name }}"
          title: "Auto-PR: Merge ${{ needs.build_and_test.outputs.branch_name }} into develop"
          body: |
            Automated PR created for branch `${{ needs.build_and_test.outputs.branch_name }}`.

            **Last Commit:** `${{ needs.build_and_test.outputs.commit_sha_short }}`
            ```
            ${{ needs.build_and_test.outputs.commit_message }}
            ```

            This PR was automatically generated after a successful build and test run on the source branch.
            Workflow run: `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
          branch: ${{ needs.build_and_test.outputs.branch_name }}
          base: develop
          labels: automated-pr # Example label, user can specify others
          # assignees: user1,user2
          # reviewers: user3,user4
          delete-branch: false # Typically set to false for automated PRs

      - name: PR Output
        if: steps.cpr.outputs.pull-request-number
        run: |
          echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"

      - name: PR Not Created (e.g. already exists and up-to-date)
        if: ${{ !steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull request was not created. This might be because one already exists and is up-to-date, or an error occurred."
          echo "Action output: ${{ steps.cpr.outputs.pull-request-operation }}"
