name: Builds
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
       dotnet-version: 8.0.x
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
    - name: Build Release 
      run: dotnet build MetarDecoder.sln --configuration Release --verbosity normal

