name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          5.0.x
          6.0.x
    - name: Update to Nuget
      run: nuget update -self
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
    - name: Build Debug 
      run: dotnet build --configuration Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Debug
