name: Builds
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 6.x
    - name: Update to Nuget
      run: nuget update -self
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
    - name: Build Release 
      run: dotnet build  --configuration Release --verbosity normal

