name: Sonarqube
on:
  workflow_dispatch:
  page_build:
  release:
    types:
      - created

jobs:
  sonarqube-analysis:

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: 8.0.x
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear
      - name: Install SonarQube Tools
        run: dotnet tool install --global --ignore-failed-sources dotnet-sonarscanner
      - name: Install Coverlet Tools
        run: dotnet tool install --global --ignore-failed-sources coverlet.console
      - name: Fix Permission
        run: chmod 777 sonar/ -R
      - name: Prepare analysis on SonarQube
        run: dotnet sonarscanner begin /o:"afonsoft" /k:"afonsoft_metar-decoder"  /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=${{secrets.SONNAR_TOKEN}} /d:sonar.scm.provider=git /d:sonar.coverage.exclusions="**Test*.cs" 
      - name: Build
        run: dotnet build MetarDecoder.sln --configuration release
      - name: Run Code Analysis
        run: dotnet sonarscanner end /d:sonar.login=${{secrets.SONNAR_TOKEN}}