name: Sonarqube
on:
  workflow_dispatch:
  page_build:
  release:
    types:
      - created

jobs:
  sonarqube-analysis:

    env:
      BUILD_CONFIG: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Update to Nuget
        run: nuget update -self
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear
      - name: Fix Permission
        run: chmod 777 sonar/ -R
      - name: Prepare analysis on SonarQube
        run: dotnet sonar/SonarScanner.MSBuild.dll begin /o:"afonsoft-github" /k:"metar-decoder" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=${{secrets.SONAR_TOKEN}} /d:sonar.scm.provider=git /d:sonar.coverage.exclusions="**Test*.cs"
      - name: Build
        run: dotnet build --configuration $BUILD_CONFIG
      - name: Run Code Analysis
        run: dotnet sonar/SonarScanner.MSBuild.dll end /d:sonar.login=${{secrets.SONAR_TOKEN}}
